### ISSUE TITLE
Analyses for body parts

### ISSUE THREAD

**Issue by LinguList** [pano-tacanan-history/zariquieypano#5]
We split them into several issues, but for now, we can have them here:

- [ ] TIGER scores (body parts vs. plain cognates)
- [ ] concordance analysis
- [ ] splitstree
- [ ] delta scores

**Comment by FredericBlum** [comment]
@LinguList Do we keep the body-part related files in this repository, or are they stored elsewhere?

**Comment by LinguList** [comment]
Can all be deleted, we moved them to https://github.com/lexibank/panobodyparts (Just had todoublecheck).
